### ISSUE TITLE
check the task is expired when taking it

### ISSUE THREAD

**Issue by kostja** [tarantool/queue#27]

**Comment by bigbes** [comment]
fixed in latest master

**Comment by rybakit** [comment]
Could you also add tests? It still fails for me: https://travis-ci.org/tarantool-php/queue/jobs/78894453.

**Comment by rybakit** [comment]
Here is what I also tried:

```lua
queue = require('queue')
queue.start()

function create_tube(tube_name, tube_type, opts)
    if nil ~= queue.tube[tube_name] then
        queue.tube[tube_name]:drop()
    end

    return queue.create_tube(tube_name, tube_type, opts)
end

function ttl(name, ttl)
    local tube = create_tube(name, 'fifottl')
    local logger = require('log')
    local fiber = require('fiber')

    tube:put(name .. '_' .. ttl, {ttl = ttl})
    fiber.sleep(ttl)
    logger.info(tube:take(.1))
end

ttl('t1', 1)
ttl('t2', 1)
ttl('t3', 1)
```

Output:

```
2015-09-08 08:43:04.606 [6332] main/105/fifottl I> Started queue fifottl fiber
2015-09-08 08:43:05.703 [6332] main/101/test.lua I> nil
2015-09-08 08:43:05.705 [6332] main/106/fifottl I> Started queue fifottl fiber
2015-09-08 08:43:06.705 [6332] main/101/test.lua I> [0, 't', 't2_1']
2015-09-08 08:43:06.706 [6332] main/107/fifottl I> Started queue fifottl fiber
2015-09-08 08:43:07.806 [6332] main/101/test.lua I> nil
```

**Comment by bigbes** [comment]
Can't reproduce..
I've replaced your
```
ttl('t1', 1)
ttl('t2', 1)
ttl('t3', 1)
```
with
```
local i = 0;$                                                                   
while true do$                                                                  
    i = i + 1$                                                                  
    ttl('t_'..i, 0.5)$                                                          
end$                                                                            
```
and i got
```
2015-09-08 14:23:20.621 [17581] main/104/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:21.223 [17581] main/101/050-ttl.t I> nil
2015-09-08 14:23:21.227 [17581] main/105/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:21.828 [17581] main/101/050-ttl.t I> nil
2015-09-08 14:23:21.829 [17581] main/106/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:22.430 [17581] main/101/050-ttl.t I> nil
2015-09-08 14:23:22.432 [17581] main/107/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:23.033 [17581] main/101/050-ttl.t I> nil
2015-09-08 14:23:23.034 [17581] main/108/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:23.635 [17581] main/101/050-ttl.t I> nil
2015-09-08 14:23:23.638 [17581] main/109/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:24.239 [17581] main/101/050-ttl.t I> nil
2015-09-08 14:23:24.240 [17581] main/110/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:24.841 [17581] main/101/050-ttl.t I> nil
2015-09-08 14:23:24.843 [17581] main/111/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:25.445 [17581] main/101/050-ttl.t I> nil
2015-09-08 14:23:25.446 [17581] main/112/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:26.047 [17581] main/101/050-ttl.t I> nil
2015-09-08 14:23:26.048 [17581] main/113/fifottl I> Started queue fifottl fiber
2015-09-08 14:23:26.650 [17581] main/101/050-ttl.t I> nil
...
```

**Comment by bigbes** [comment]
What's your OS? maybe this is something libev and your platform specific.

**Comment by rybakit** [comment]
```
Linux vagrant-ubuntu-trusty-64 3.13.0-54-generic #91-Ubuntu SMP Tue May 26 19:15:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```
Tarantool 1.6.7-56-g9da4ff1
Target: Linux-x86_64-RelWithDebugInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_TRACE=ON -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/x86_64-linux-gnu-gcc /usr/bin/x86_64-linux-gnu-g++
C_FLAGS: -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -fno-gnu89-inline
CXX_FLAGS: -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -Wno-invalid-offsetof
```

**Comment by bigbes** [comment]
Ok, i've taken Ubuntu Trusty Vagrant box, and tried to reproduce and i've failed again.
there were two tests:

```
queue = require('queue')

box.cfg{}

queue.start()

function create_tube(tube_name, tube_type, opts)
    if nil ~= queue.tube[tube_name] then
        queue.tube[tube_name]:drop()
    end

    return queue.create_tube(tube_name, tube_type, opts)
end

function ttl_1(name, ttl)
    local tube = create_tube(name, 'fifottl')
    local logger = require('log')
    local fiber = require('fiber')

    tube:put(name .. '_' .. ttl, {ttl = ttl})
    fiber.sleep(ttl)
    logger.info(tube:take(.1))
end

function ttl_2(name, ttl)
    local tube = create_tube(name, 'fifottl')
    local logger = require('log')
    local fiber = require('fiber')
    while true do
        tube:put(name .. '_' .. ttl, {ttl = ttl})
        fiber.sleep(ttl)
        logger.info(tube:take(.1))
    end
end

function ttl_test_1()
    local i = 0
    while true do
        ttl_1('t_' .. i, 1)
        i = i + 1
    end
end

function ttl_test_2()
    ttl_2('t', 1)
end
```
1) `ttl_test_1` - start new queue every second (with task whose ttl = 1 sec)
2) `ttl_test_2` - add new task every second (with ttl = 1 sec)

**Comment by kostja** [comment]
Йф!ф!ф
,
